#!/usr/bin/env python3
"""PreCompact hook: preserve context before compaction.

Reads transcript path from stdin JSON, backs up transcript,
extracts working context summary, writes to memory dir.
Always exits 0.
"""

from __future__ import annotations

import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path


def _log(log_file: Path, msg: str) -> None:
    try:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().astimezone().isoformat(timespec="seconds")
        with open(log_file, "a") as f:
            f.write(f"{ts} pre-compact: {msg}\n")
    except OSError:
        pass


def parse_transcript(path: Path) -> tuple[list[str], list[str]]:
    user_msgs: list[str] = []
    files_touched: set[str] = set()

    try:
        for line in path.read_text().splitlines():
            if not line.strip():
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            role = obj.get("role", "")
            content = obj.get("content", "")

            if role == "user" and isinstance(content, str) and len(content.strip()) > 15:
                user_msgs.append(content.strip()[:200])

            if role == "assistant" and isinstance(content, list):
                for block in content:
                    if not isinstance(block, dict) or block.get("type") != "tool_use":
                        continue
                    inp = block.get("input", {})
                    for key in ("file_path", "path"):
                        val = inp.get(key, "")
                        if isinstance(val, str) and "/" in val:
                            files_touched.add(val)
    except OSError:
        pass

    return user_msgs, sorted(files_touched)


def build_summary(user_msgs: list[str], files: list[str]) -> str:
    parts: list[str] = []
    if user_msgs:
        parts.append("## Tasks in progress")
        for msg in user_msgs[-5:]:
            parts.append(f"- {msg}")
    if files:
        parts.append("\n## Files worked on")
        for f in files[-10:]:
            parts.append(f"- {f}")
    return "\n".join(parts)


def main() -> None:
    try:
        input_data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError, ValueError):
        input_data = {}

    cwd = Path.cwd()
    claude_dir = Path(os.environ.get("CLAUDE_CONFIG_DIR", Path.home() / ".claude"))
    log_file = claude_dir / "logs" / "hooks.log"
    _log(log_file, f"fired cwd={cwd}")

    transcript_path_str = ""
    for key in ("transcript_path", "transcriptPath", "input"):
        if key in input_data:
            transcript_path_str = input_data[key]
            break

    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    memory_dir = claude_dir / "projects" / encoded / "memory"
    memory_dir.mkdir(parents=True, exist_ok=True)

    summary = ""

    if transcript_path_str:
        transcript_path = Path(transcript_path_str)
        if transcript_path.is_file():
            backup_dir = claude_dir / "compact-backups"
            backup_dir.mkdir(parents=True, exist_ok=True)
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            proj_name = cwd.name
            backup_file = backup_dir / f"{ts}-{proj_name}.jsonl"
            try:
                shutil.copy2(transcript_path, backup_file)
                _log(log_file, f"backed up transcript to {backup_file.name}")
            except OSError as e:
                _log(log_file, f"backup failed: {e}")

            user_msgs, files = parse_transcript(transcript_path)
            summary = build_summary(user_msgs, files)

    if summary:
        summary_file = memory_dir / "pre-compact-summary.md"
        ts = datetime.now().isoformat()
        try:
            summary_file.write_text(
                f"<!-- auto-generated by pre-compact hook at {ts} -->\n{summary}\n"
            )
            _log(log_file, f"summary written ({len(summary)} chars)")
        except OSError as e:
            _log(log_file, f"summary write failed: {e}")

        output = {
            "hookSpecificOutput": {
                "hookEventName": "PreCompact",
                "additionalContext": summary,
            }
        }
        print(json.dumps(output))
    else:
        _log(log_file, "no summary extracted")


if __name__ == "__main__":
    main()
