"""Generate a profile's system-instruction doc by concatenating its segments.

Profiles can opt into a segmented layout where the agent-loaded system doc is
assembled from pieces named by **role**, not by the destination's filename:

    <profile>/head.md          identity / per-profile preamble
    _common/common.md          shared rules
    _common/<agent>.md         agent-specific rules, shared across profiles
    <profile>/tail.md          per-profile context

`sync_profiles` regenerates every destination `system_docs()` names from those
pieces. It is a no-op for profiles that carry no segments — callers can run it
across an entire `profiles/` tree without breaking flat profiles.

The destinations come from `system_docs()` on the adapter that *that profile*
runs, so one tree can hold profiles with different ones:

  Claude Code → [CLAUDE.md]
  Codex       → [AGENTS.md]
  Agents without a system doc return [] — those profiles are skipped.

An adapter may name more than one destination. One document is rendered and
written to each of them, byte for byte: a destination is where the agent looks,
not a variant of the content (ADR-043).

The legacy stem-keyed layout no longer renders. A directory carrying only
`CLAUDE.head.md`, `_common/CLAUDE.common.md`, and `CLAUDE.tail.md` is skipped,
and the result names the legacy head and `lh profile migrate` as the only path
back into the assembler. A tree carrying both layouts uses the role-named one:
the legacy files are leftovers and are never read.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from lazy_harness import __version__
from lazy_harness.agents.base import AgentAdapter

if TYPE_CHECKING:
    from collections.abc import Sequence

    from lazy_harness.core.config import Config

# The role names, in one importable place. `segment_filenames()` derives the
# sync hook's trigger set from them rather than from a second list, because a
# static list is how a renamed segment stops firing the hook that regenerates
# it — silently, in the one file whose whole purpose is to be authoritative.
HEAD_SEGMENT = "head.md"
COMMON_SEGMENT = "common.md"
TAIL_SEGMENT = "tail.md"

ROLE_SEGMENT_NAMES = (HEAD_SEGMENT, f"_common/{COMMON_SEGMENT}", TAIL_SEGMENT)

# The version is embedded so a reader can tell a doc written by an older or
# newer harness apart from one matching the running binary (decision 9,
# 2026-09-13 multi-agent blast radius design). `lazy_harness.core.artifact_version`
# parses it back out with the same "lazy-harness <version>" marker text used
# in the `.envrc` block notice.
GENERATED_HEADER_TMPL = (
    "<!-- GENERATED by `lh profile sync-system-doc` (lazy-harness {version}) — "
    "edit {segments} instead -->"
)


def legacy_segment_names(stem: str) -> tuple[str, str, str]:
    """The pre-ADR-043 segment names for a destination stem."""
    return (f"{stem}.head.md", f"_common/{stem}.common.md", f"{stem}.tail.md")


def segment_filenames() -> frozenset[str]:
    """Every basename whose edit must trigger a resync.

    Derived from the roles above plus the registry: one agent segment per
    registered agent. Legacy spellings are not inputs, so editing one must not
    trigger a resync.
    """
    from lazy_harness.agents.registry import get_agent, list_agents

    names = {HEAD_SEGMENT, COMMON_SEGMENT, TAIL_SEGMENT}
    for agent_type in list_agents():
        if not get_agent(agent_type).system_docs():
            continue
        names.add(f"{agent_type}.md")
    return frozenset(names)


class SyncError(Exception):
    """Raised when profile-tree state prevents sync (e.g. missing _common)."""


@dataclass
class SyncResult:
    profile: str
    action: str  # "written", "unchanged", "skipped", "orphaned"
    path: Path
    reason: str = ""


def render_agent_md(
    head: str,
    common: str,
    tail: str,
    *,
    agent: str = "",
    names: Sequence[str] = ROLE_SEGMENT_NAMES,
) -> str:
    """Compose head + common + agent + tail under a generated header.

    `names` is what the header tells the reader to edit, so it spells the
    layout actually read — a header naming `head.md` on a tree that still has
    `CLAUDE.head.md` sends the reader to a file that is not there.
    """
    header = GENERATED_HEADER_TMPL.format(segments=" / ".join(names), version=__version__)
    parts = [header, "", head, "", common]
    if agent:
        parts += ["", agent]
    parts += ["---", "", tail]
    return "\n".join(parts)


@dataclass(frozen=True)
class _Layout:
    """The segments one profile directory is assembled from."""

    head: Path
    tail: Path
    common_name: str  # inside `_common/`

    def names(self, agent_segment: Path | None) -> tuple[str, ...]:
        parts = [self.head.name, f"_common/{self.common_name}"]
        if agent_segment is not None:
            parts.append(f"_common/{agent_segment.name}")
        parts.append(self.tail.name)
        return tuple(parts)


def _layout_for(entry: Path, stem: str) -> _Layout | None:
    if (entry / HEAD_SEGMENT).is_file():
        return _Layout(
            head=entry / HEAD_SEGMENT,
            tail=entry / TAIL_SEGMENT,
            common_name=COMMON_SEGMENT,
        )
    return None


def _agent_segment(profiles_dir: Path, agent_name: str) -> Path | None:
    """`_common/<agent>.md`, shared across profiles, absent for most agents.

    Shared rather than per profile because that is what the deployed tree
    measures: every agent-specific line already lives in the shared segment
    and none in any profile's head or tail. A per-profile override is
    additive to this layout and costs nothing to add when a second profile
    needs to say something different about the same agent.
    """
    path = profiles_dir / "_common" / f"{agent_name}.md"
    return path if path.is_file() else None


def available_system_doc_sources(
    source_dir: Path, profiles_dir: Path, agent: AgentAdapter
) -> tuple[Path, ...]:
    """Source files deploy's assembler can use for this agent's system document."""
    docs = agent.system_docs()
    if not docs:
        return ()
    layout = _layout_for(source_dir, docs[0].stem)
    if layout is None:
        flat = tuple(source_dir / doc for doc in docs)
        return flat if all(path.is_file() for path in flat) else ()
    common = profiles_dir / "_common" / layout.common_name
    sources = (layout.head, common, layout.tail)
    if not all(path.is_file() for path in sources):
        return ()
    agent_segment = _agent_segment(profiles_dir, agent.name)
    if agent_segment is not None:
        return (layout.head, common, agent_segment, layout.tail)
    return sources


@dataclass(frozen=True)
class _SyncJob:
    """One (source dir, agent) pair to render and write — the unit a profile
    or a group of profiles sharing an identity and agent resolves to."""

    label: str
    source_dir: Path
    docs: tuple[Path, ...]
    agent_name: str


def _render_jobs(profiles_dir: Path, jobs: list[_SyncJob]) -> list[SyncResult]:
    """Render and write each job's document once, atomically across `jobs`.

    Every shared segment this scope needs is loaded before the first write, so
    a missing common segment refuses the whole selected scope rather than
    leaving it half-synced.
    """
    commons: dict[str, str] = {}

    def _common_for(name: str) -> str:
        if name not in commons:
            common_path = profiles_dir / "_common" / name
            if not common_path.is_file():
                raise SyncError(f"missing {common_path}")
            commons[name] = common_path.read_text()
        return commons[name]

    prepared: list[tuple[_SyncJob, str, _Layout | None]] = []
    for job in jobs:
        if not job.docs or not job.source_dir.is_dir():
            continue
        stem = job.docs[0].name.removesuffix(".md")
        prepared.append((job, stem, _layout_for(job.source_dir, stem)))

    for _job, _stem, layout in prepared:
        if layout is not None:
            _common_for(layout.common_name)

    results: list[SyncResult] = []
    for job, stem, layout in prepared:
        if layout is None:
            # Flat profile: a hand-written doc the generator must not erase.
            # Reported rather than passed over, because "no segments" and "not
            # a profile dir" look the same to a reader of the command's output.
            legacy_head = legacy_segment_names(stem)[0] if stem else ""
            if legacy_head and (job.source_dir / legacy_head).is_file():
                reason = f"legacy segments ({legacy_head}) — run lh profile migrate {job.label}"
            else:
                reason = f"missing {HEAD_SEGMENT}"
            results.append(
                SyncResult(
                    profile=job.label,
                    action="skipped",
                    path=job.source_dir / job.docs[0],
                    reason=reason,
                )
            )
            continue
        if not layout.tail.is_file():
            results.append(
                SyncResult(
                    profile=job.label,
                    action="skipped",
                    path=job.source_dir / job.docs[0],
                    reason=f"missing {layout.tail.name}",
                )
            )
            continue

        agent_path = _agent_segment(profiles_dir, job.agent_name)
        new_content = render_agent_md(
            layout.head.read_text(),
            _common_for(layout.common_name),
            layout.tail.read_text(),
            agent=agent_path.read_text() if agent_path is not None else "",
            names=layout.names(agent_path),
        )
        # One rendered document, N destinations (ADR-043). Every job gets the
        # identical bytes: a destination is where the agent looks, not a variant
        # of the content. A nested destination brings its own directory, which
        # the deployer would otherwise have to guess at.
        for rel in job.docs:
            out = job.source_dir / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            if out.is_file() and out.read_text() == new_content:
                results.append(SyncResult(profile=job.label, action="unchanged", path=out))
                continue
            out.write_text(new_content)
            results.append(SyncResult(profile=job.label, action="written", path=out))
    return results


def _sync_directory_driven(
    profiles_dir: Path, adapter: AgentAdapter, *, only: str | None
) -> list[SyncResult]:
    """Pre-identity behaviour: one directory is one profile is one agent.

    `adapter` answers for every directory alike, including ones a config no
    longer names — the only mode available without a `cfg` to resolve one.
    """
    docs = tuple(adapter.system_docs())
    entries = [
        entry
        for entry in sorted(profiles_dir.iterdir())
        if entry.is_dir()
        and not entry.name.startswith("_")
        and (only is None or entry.name == only)
    ]
    jobs = [_SyncJob(entry.name, entry, docs, adapter.name) for entry in entries]
    return _render_jobs(profiles_dir, jobs)


def _sync_config_driven(
    profiles_dir: Path, cfg: Config, adapter: AgentAdapter, *, only: str | None
) -> list[SyncResult]:
    """Iterates configured profiles rather than directories (design section 3).

    Two profiles that share `(identity, agent)` resolve to one job — one
    write, not a race or a duplicate. A directory under `profiles_dir` no
    configured profile resolves to is reported `orphaned` and never touched,
    but only once at least one profile in `cfg` declares `identity`: until
    then an identity-less config can't tell an orphan from a directory that
    simply predates `identity` as a concept, so it keeps the pre-identity
    fallback — synced with `adapter`, the caller's own (M3). The same split
    applies to `only` naming a directory `cfg` does not carry: it raises once
    identity is declared anywhere, and is synced with `adapter` until then —
    never silently returning `[]`.
    """
    from lazy_harness.agents.registry import agent_for_profile
    from lazy_harness.core.profile_identity import profile_identity, profile_source_dir

    has_identity = any(entry.identity for entry in cfg.profiles.items.values())
    claimed = {profile_source_dir(cfg, name, profiles_dir).resolve() for name in cfg.profiles.items}

    if only is not None and only not in cfg.profiles.items:
        if has_identity:
            raise SyncError(f"no configured profile named {only!r}")
        return _sync_directory_driven(profiles_dir, adapter, only=only)

    selected_names = [only] if only is not None else list(cfg.profiles.items)
    seen: set[tuple[Path, str]] = set()
    jobs: list[_SyncJob] = []
    for name in selected_names:
        entry = cfg.profiles.items.get(name)
        if entry is None:
            continue
        agent = agent_for_profile(cfg, name)
        docs = tuple(agent.system_docs())
        if not docs:
            continue
        source_dir = profile_source_dir(cfg, name, profiles_dir)
        key = (source_dir, agent.name)
        if key in seen:
            continue
        seen.add(key)
        jobs.append(_SyncJob(profile_identity(name, entry), source_dir, docs, agent.name))

    results = _render_jobs(profiles_dir, jobs)

    if only is None:
        fallback_docs = tuple(adapter.system_docs())
        for entry_dir in sorted(profiles_dir.iterdir()):
            if not entry_dir.is_dir() or entry_dir.name.startswith("_"):
                continue
            if entry_dir.resolve() in claimed:
                continue
            if has_identity:
                results.append(
                    SyncResult(profile=entry_dir.name, action="orphaned", path=entry_dir)
                )
            else:
                fallback_job = _SyncJob(entry_dir.name, entry_dir, fallback_docs, adapter.name)
                results.extend(_render_jobs(profiles_dir, [fallback_job]))
    return results


def sync_profiles(
    profiles_dir: Path,
    adapter: AgentAdapter,
    *,
    cfg: Config | None = None,
    only: str | None = None,
) -> list[SyncResult]:
    """Regenerate the system doc for every profile `profiles_dir` holds.

    Without `cfg`, one directory is one profile is one agent (`adapter`
    answers for all of them) — the behaviour every caller had before profile
    identity existed. With `cfg`, profiles are iterated instead of
    directories: destinations are per profile's own agent
    (`agent_for_profile`), two profiles sharing an identity and agent write
    once. A directory no configured profile resolves to is reported
    `orphaned` and left untouched once at least one profile in `cfg` declares
    `identity`; until then it keeps the pre-identity fallback of being synced
    with `adapter`, the caller's own (design section 3 / M3). `only` narrows
    either mode to one profile; no sibling profile is read or written.

    Skips a profile whose adapter declares no system doc, and one that
    carries no role-named segments. A profile carrying head and tail without
    the shared segment is still the loud failure it always was.
    """
    if cfg is None:
        return _sync_directory_driven(profiles_dir, adapter, only=only)
    return _sync_config_driven(profiles_dir, cfg, adapter, only=only)
