"""Generate per-profile system-instruction doc by concatenating head + common + tail.

Profiles can opt into a segmented layout where the agent-loaded system doc
is split into three pieces:

    <profile>/<stem>.head.md   identity / per-profile preamble
    _common/<stem>.common.md   shared rules
    <profile>/<stem>.tail.md   per-profile context

`sync_profiles` regenerates `<profile>/<doc_name>` from those pieces. It is a
no-op for profiles that don't carry the three files — callers can run it across
an entire `profiles/` tree without breaking flat profiles.

The filename (<doc_name>) is determined by `adapter.system_doc_name()`:
  Claude Code → CLAUDE.md   (stem: CLAUDE)
  Gemini CLI  → GEMINI.md   (stem: GEMINI)
  Agents without a system doc return "" — `sync_profiles` becomes a no-op.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from lazy_harness.agents.base import AgentAdapter

GENERATED_HEADER_TMPL = (
    "<!-- GENERATED by `lh profile sync-agent-md` — "
    "edit {stem}.head.md / _common/{stem}.common.md / {stem}.tail.md instead -->"
)


class SyncError(Exception):
    """Raised when profile-tree state prevents sync (e.g. missing _common)."""


@dataclass
class SyncResult:
    profile: str
    action: str  # "written", "unchanged", "skipped"
    path: Path
    reason: str = ""


def render_agent_md(stem: str, head: str, common: str, tail: str) -> str:
    header = GENERATED_HEADER_TMPL.format(stem=stem)
    parts = [header, "", head, "", common, "---", "", tail]
    return "\n".join(parts)


def sync_profiles(profiles_dir: Path, adapter: AgentAdapter) -> list[SyncResult]:
    """Regenerate the system doc for every profile under `profiles_dir`.

    Skips the entire tree if `adapter.system_doc_name()` is empty (the adapter
    does not use a file-based system instruction doc).
    """
    doc_name = adapter.system_doc_name()
    if not doc_name:
        return []

    stem = doc_name.removesuffix(".md")
    common_path = profiles_dir / "_common" / f"{stem}.common.md"
    if not common_path.is_file():
        raise SyncError(f"missing {common_path}")
    common = common_path.read_text()

    results: list[SyncResult] = []
    for entry in sorted(profiles_dir.iterdir()):
        if not entry.is_dir() or entry.name.startswith("_"):
            continue
        head = entry / f"{stem}.head.md"
        tail = entry / f"{stem}.tail.md"
        out = entry / doc_name

        if not head.is_file() or not tail.is_file():
            missing = f"{stem}.head.md" if not head.is_file() else f"{stem}.tail.md"
            results.append(
                SyncResult(
                    profile=entry.name,
                    action="skipped",
                    path=out,
                    reason=f"missing {missing}",
                )
            )
            continue

        new_content = render_agent_md(stem, head.read_text(), common, tail.read_text())
        if out.is_file() and out.read_text() == new_content:
            results.append(SyncResult(profile=entry.name, action="unchanged", path=out))
            continue
        out.write_text(new_content)
        results.append(SyncResult(profile=entry.name, action="written", path=out))
    return results
