"""Generate a profile's system-instruction doc by concatenating its segments.

Profiles can opt into a segmented layout where the agent-loaded system doc is
assembled from pieces named by **role**, not by the destination's filename:

    <profile>/head.md          identity / per-profile preamble
    _common/common.md          shared rules
    _common/<agent>.md         agent-specific rules, shared across profiles
    <profile>/tail.md          per-profile context

`sync_profiles` regenerates every destination `system_docs()` names from those
pieces. It is a no-op for profiles that carry no segments — callers can run it
across an entire `profiles/` tree without breaking flat profiles.

The destinations come from `system_docs()` on the adapter that *that profile*
runs, so one tree can hold profiles with different ones:

  Claude Code → [CLAUDE.md]
  Codex       → [AGENTS.md]
  Agents without a system doc return [] — those profiles are skipped.

An adapter may name more than one destination. One document is rendered and
written to each of them, byte for byte: a destination is where the agent looks,
not a variant of the content (ADR-043).

The legacy stem-keyed layout no longer renders. A directory carrying only
`CLAUDE.head.md`, `_common/CLAUDE.common.md`, and `CLAUDE.tail.md` is skipped,
and the result names the legacy head and `lh profile migrate` as the only path
back into the assembler. A tree carrying both layouts uses the role-named one:
the legacy files are leftovers and are never read.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from lazy_harness import __version__
from lazy_harness.agents.base import AgentAdapter

if TYPE_CHECKING:
    from collections.abc import Sequence

    from lazy_harness.core.config import Config

# The role names, in one importable place. `segment_filenames()` derives the
# sync hook's trigger set from them rather than from a second list, because a
# static list is how a renamed segment stops firing the hook that regenerates
# it — silently, in the one file whose whole purpose is to be authoritative.
HEAD_SEGMENT = "head.md"
COMMON_SEGMENT = "common.md"
TAIL_SEGMENT = "tail.md"

ROLE_SEGMENT_NAMES = (HEAD_SEGMENT, f"_common/{COMMON_SEGMENT}", TAIL_SEGMENT)

# The version is embedded so a reader can tell a doc written by an older or
# newer harness apart from one matching the running binary (decision 9,
# 2026-09-13 multi-agent blast radius design). `lazy_harness.core.artifact_version`
# parses it back out with the same "lazy-harness <version>" marker text used
# in the `.envrc` block notice.
GENERATED_HEADER_TMPL = (
    "<!-- GENERATED by `lh profile sync-system-doc` (lazy-harness {version}) — "
    "edit {segments} instead -->"
)


def legacy_segment_names(stem: str) -> tuple[str, str, str]:
    """The pre-ADR-043 segment names for a destination stem."""
    return (f"{stem}.head.md", f"_common/{stem}.common.md", f"{stem}.tail.md")


def segment_filenames() -> frozenset[str]:
    """Every basename whose edit must trigger a resync.

    Derived from the roles above plus the registry: one agent segment per
    registered agent. Legacy spellings are not inputs, so editing one must not
    trigger a resync.
    """
    from lazy_harness.agents.registry import get_agent, list_agents

    names = {HEAD_SEGMENT, COMMON_SEGMENT, TAIL_SEGMENT}
    for agent_type in list_agents():
        if not get_agent(agent_type).system_docs():
            continue
        names.add(f"{agent_type}.md")
    return frozenset(names)


class SyncError(Exception):
    """Raised when profile-tree state prevents sync (e.g. missing _common)."""


@dataclass
class SyncResult:
    profile: str
    action: str  # "written", "unchanged", "skipped"
    path: Path
    reason: str = ""


def render_agent_md(
    head: str,
    common: str,
    tail: str,
    *,
    agent: str = "",
    names: Sequence[str] = ROLE_SEGMENT_NAMES,
) -> str:
    """Compose head + common + agent + tail under a generated header.

    `names` is what the header tells the reader to edit, so it spells the
    layout actually read — a header naming `head.md` on a tree that still has
    `CLAUDE.head.md` sends the reader to a file that is not there.
    """
    header = GENERATED_HEADER_TMPL.format(segments=" / ".join(names), version=__version__)
    parts = [header, "", head, "", common]
    if agent:
        parts += ["", agent]
    parts += ["---", "", tail]
    return "\n".join(parts)


@dataclass(frozen=True)
class _Layout:
    """The segments one profile directory is assembled from."""

    head: Path
    tail: Path
    common_name: str  # inside `_common/`

    def names(self, agent_segment: Path | None) -> tuple[str, ...]:
        parts = [self.head.name, f"_common/{self.common_name}"]
        if agent_segment is not None:
            parts.append(f"_common/{agent_segment.name}")
        parts.append(self.tail.name)
        return tuple(parts)


def sync_profiles(
    profiles_dir: Path,
    adapter: AgentAdapter,
    *,
    cfg: Config | None = None,
    only: str | None = None,
) -> list[SyncResult]:
    """Regenerate the system doc for every profile under `profiles_dir`.

    Skips a profile whose adapter declares no system doc (the adapter does not
    use a file-based system instruction doc), and one that carries no role-named
    segments. When `only` is set, no sibling profile is read or written.

    `cfg` resolves each directory's adapter through `agent_for_profile`, which
    is what makes the destinations per profile. Without it every directory in
    the tree got one agent's contract file — `adapter` was read once, above this
    loop, so a profile running an agent that loads `AGENTS.md` was handed a
    `CLAUDE.md` and the file it actually reads was never written. `adapter`
    stays as the answer for a directory the config does not name: the tree can
    hold profiles that were removed from `config.toml` but not from disk.

    A profile carrying head and tail without the shared segment is still the
    loud failure it always was.
    """
    resolved: dict[str, tuple[list[Path], str, str]] = {}

    def _agent_for(profile: str) -> tuple[list[Path], str, str]:
        """(destinations, stem, agent name) for one profile dir, resolved once."""
        if profile not in resolved:
            agent = adapter
            # Only a directory the config actually declares resolves through
            # `agent_for_profile`: that call falls back to `[agent].type` for an
            # unknown name, which would hand a leftover directory the *global*
            # agent rather than the caller's. The hook fires under one profile
            # and walks a tree that may hold directories for profiles since
            # removed from `config.toml`; those keep the caller's answer.
            if cfg is not None and profile in cfg.profiles.items:
                from lazy_harness.agents.registry import agent_for_profile

                agent = agent_for_profile(cfg, profile)
            docs = agent.system_docs()
            stem = docs[0].name.removesuffix(".md") if docs else ""
            resolved[profile] = (docs, stem, agent.name)
        return resolved[profile]

    commons: dict[str, str] = {}

    def _common_for(name: str) -> str:
        if name not in commons:
            common_path = profiles_dir / "_common" / name
            if not common_path.is_file():
                raise SyncError(f"missing {common_path}")
            commons[name] = common_path.read_text()
        return commons[name]

    def _layout_for(entry: Path, stem: str) -> _Layout | None:
        if (entry / HEAD_SEGMENT).is_file():
            return _Layout(
                head=entry / HEAD_SEGMENT,
                tail=entry / TAIL_SEGMENT,
                common_name=COMMON_SEGMENT,
            )
        return None

    def _entries() -> list[Path]:
        return [
            entry
            for entry in sorted(profiles_dir.iterdir())
            if entry.is_dir()
            and not entry.name.startswith("_")
            and (only is None or entry.name == only)
        ]

    def _agent_segment(agent_name: str) -> Path | None:
        """`_common/<agent>.md`, shared across profiles, absent for most agents.

        Shared rather than per profile because that is what the deployed tree
        measures: every agent-specific line already lives in the shared segment
        and none in any profile's head or tail. A per-profile override is
        additive to this layout and costs nothing to add when a second profile
        needs to say something different about the same agent.
        """
        path = profiles_dir / "_common" / f"{agent_name}.md"
        return path if path.is_file() else None

    # Every shared segment this tree needs is loaded before the first write, so
    # a missing common segment refuses the whole selected scope atomically.
    entries = _entries()
    for entry in entries:
        docs, stem, _ = _agent_for(entry.name)
        if not docs:
            continue
        layout = _layout_for(entry, stem)
        if layout is not None:
            _common_for(layout.common_name)

    results: list[SyncResult] = []
    for entry in entries:
        docs, stem, agent_name = _agent_for(entry.name)
        if not docs:
            continue
        layout = _layout_for(entry, stem)
        if layout is None:
            # Flat profile: a hand-written doc the generator must not erase.
            # Reported rather than passed over, because "no segments" and "not
            # a profile dir" look the same to a reader of the command's output.
            legacy_head = legacy_segment_names(stem)[0] if stem else ""
            if legacy_head and (entry / legacy_head).is_file():
                reason = f"legacy segments ({legacy_head}) — run lh profile migrate {entry.name}"
            else:
                reason = f"missing {HEAD_SEGMENT}"
            results.append(
                SyncResult(
                    profile=entry.name,
                    action="skipped",
                    path=entry / docs[0],
                    reason=reason,
                )
            )
            continue
        if not layout.tail.is_file():
            results.append(
                SyncResult(
                    profile=entry.name,
                    action="skipped",
                    path=entry / docs[0],
                    reason=f"missing {layout.tail.name}",
                )
            )
            continue

        agent_path = _agent_segment(agent_name)
        new_content = render_agent_md(
            layout.head.read_text(),
            _common_for(layout.common_name),
            layout.tail.read_text(),
            agent=agent_path.read_text() if agent_path is not None else "",
            names=layout.names(agent_path),
        )
        # One rendered document, N destinations (ADR-043). Every entry gets the
        # identical bytes: a destination is where the agent looks, not a variant
        # of the content. A nested destination brings its own directory, which
        # the deployer would otherwise have to guess at.
        for rel in docs:
            out = entry / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            if out.is_file() and out.read_text() == new_content:
                results.append(SyncResult(profile=entry.name, action="unchanged", path=out))
                continue
            out.write_text(new_content)
            results.append(SyncResult(profile=entry.name, action="written", path=out))
    return results
