"""Generate per-profile CLAUDE.md by concatenating head + common + tail.

Profiles can opt into a segmented layout where the agent-loaded `CLAUDE.md`
is split into three pieces:

    <profile>/CLAUDE.head.md   identity / per-profile preamble
    _common/CLAUDE.common.md   shared rules
    <profile>/CLAUDE.tail.md   per-profile context

`sync_profiles` regenerates `<profile>/CLAUDE.md` from those pieces. It is a
no-op for profile dirs that don't carry the three files — callers can run it
across an entire `profiles/` tree without breaking flat profiles.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

GENERATED_HEADER = (
    "<!-- GENERATED by `lh profile sync-claude-md` — "
    "edit CLAUDE.head.md / _common/CLAUDE.common.md / CLAUDE.tail.md instead -->"
)


class SyncError(Exception):
    """Raised when profile-tree state prevents sync (e.g. missing _common)."""


@dataclass
class SyncResult:
    profile: str
    action: str  # "written", "unchanged", "skipped"
    path: Path
    reason: str = ""


def render_claude_md(head: str, common: str, tail: str) -> str:
    parts = [GENERATED_HEADER, "", head, "", common, "---", "", tail]
    return "\n".join(parts)


def sync_profiles(profiles_dir: Path) -> list[SyncResult]:
    common_path = profiles_dir / "_common" / "CLAUDE.common.md"
    if not common_path.is_file():
        raise SyncError(f"missing {common_path}")
    common = common_path.read_text()

    results: list[SyncResult] = []
    for entry in sorted(profiles_dir.iterdir()):
        if not entry.is_dir() or entry.name.startswith("_"):
            continue
        head = entry / "CLAUDE.head.md"
        tail = entry / "CLAUDE.tail.md"
        out = entry / "CLAUDE.md"

        if not head.is_file() or not tail.is_file():
            missing = "CLAUDE.head.md" if not head.is_file() else "CLAUDE.tail.md"
            results.append(
                SyncResult(
                    profile=entry.name,
                    action="skipped",
                    path=out,
                    reason=f"missing {missing}",
                )
            )
            continue

        new_content = render_claude_md(head.read_text(), common, tail.read_text())
        if out.is_file() and out.read_text() == new_content:
            results.append(SyncResult(profile=entry.name, action="unchanged", path=out))
            continue
        out.write_text(new_content)
        results.append(SyncResult(profile=entry.name, action="written", path=out))
    return results
