"""Bounded PRJ session snapshot (ADR-062).

The compound-loop worker may replace exactly one generated `## Última sesión`
section in a LazyMind project readme. It never creates the section, never
touches a human-curated one, and leaves the file byte-identical when the
rendered section has not changed — so frontmatter `updated` moves only with
real content.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

SECTION_HEADER = "## Última sesión"

_UPDATED_LINE = re.compile(r"^updated:.*$", re.MULTILINE)
_H2_LINE = re.compile(r"^## ", re.MULTILINE)


@dataclass(frozen=True)
class ProjectUpdate:
    summary: str
    completed: tuple[str, ...] = ()
    next: tuple[str, ...] = ()
    references: tuple[str, ...] = ()


@dataclass(frozen=True)
class Provenance:
    session_id: str
    timestamp: str
    revision: str


@dataclass(frozen=True)
class SyncResult:
    written: bool
    reason: str


def _clean_items(raw: object) -> tuple[str, ...] | None:
    """A list of strings with blanks dropped; None when the shape is wrong.

    A blank item is noise, not a defect: it is dropped. A non-string item is
    a defect and refuses the whole list."""
    if raw is None:
        return ()
    if not isinstance(raw, list):
        return None
    items: list[str] = []
    for item in raw:
        if not isinstance(item, str):
            return None
        stripped = item.strip()
        if stripped:
            items.append(stripped)
    return tuple(items)


def parse_project_update(raw: object) -> ProjectUpdate | None:
    """Validate an LLM-emitted `project_update`; None on any shape defect.

    The result is untrusted output: a wrong type anywhere refuses the whole
    update rather than writing a partial snapshot into the PRJ.
    """
    if not isinstance(raw, dict):
        return None
    summary = raw.get("summary")
    if not isinstance(summary, str) or not summary.strip():
        return None
    lists: dict[str, tuple[str, ...]] = {}
    for key in ("completed", "next", "references"):
        cleaned = _clean_items(raw.get(key))
        if cleaned is None:
            return None
        lists[key] = cleaned
    return ProjectUpdate(
        summary=summary.strip(),
        completed=lists["completed"],
        next=lists["next"],
        references=lists["references"],
    )


def _demote_h2(text: str) -> str:
    """Keep model text from opening a new H2 — that would end the bounded section."""
    return _H2_LINE.sub("\\## ", text)


def render_section(update: ProjectUpdate, provenance: Provenance) -> str:
    short_id = provenance.session_id[:8] or "unknown"
    lines = [
        SECTION_HEADER,
        "",
        f"<!-- generated by lazy-harness: session {short_id} · "
        f"{provenance.timestamp} · rev {provenance.revision} -->",
        "",
        _demote_h2(update.summary),
    ]
    for title, items in (
        ("Completado", update.completed),
        ("Próximo", update.next),
        ("Referencias", update.references),
    ):
        if not items:
            continue
        lines.extend(["", f"**{title}**", ""])
        lines.extend(f"- {_demote_h2(item)}" for item in items)
    return "\n".join(lines) + "\n"


def _section_bounds(text: str) -> tuple[int, int] | None:
    """Start of the header line and start of the next H2 (or EOF)."""
    for match in re.finditer(r"^" + re.escape(SECTION_HEADER) + r"[ \t]*$", text, re.MULTILINE):
        start = match.start()
        nxt = _H2_LINE.search(text, match.end())
        return start, (nxt.start() if nxt else len(text))
    return None


def replace_section(text: str, section: str) -> str | None:
    """Swap the generated section for `section`; None when the PRJ has none.

    The section runs from its header line to the next H2. A trailing blank
    line is kept so the following heading stays separated.
    """
    bounds = _section_bounds(text)
    if bounds is None:
        return None
    start, end = bounds
    replacement = section if end == len(text) else section + "\n"
    return text[:start] + replacement + text[end:]


def _frontmatter_end(text: str) -> int | None:
    if not text.startswith("---\n"):
        return None
    close = text.find("\n---\n", 4)
    return None if close == -1 else close + 1


def bump_updated(text: str, date_str: str) -> str:
    """Rewrite the frontmatter `updated:` field; unchanged when there is none."""
    end = _frontmatter_end(text)
    if end is None:
        return text
    front, body = text[:end], text[end:]
    return _UPDATED_LINE.sub(f"updated: {date_str}", front, count=1) + body


def _atomic_write(path: Path, content: str) -> None:
    tmp = path.with_name(f".{path.name}.tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)


def sync_last_session(
    prj_md: Path, update: ProjectUpdate, provenance: Provenance, *, date_str: str
) -> SyncResult:
    """Replace the generated section when it changed; every refusal is named."""
    try:
        original = prj_md.read_text(encoding="utf-8")
    except OSError as e:
        return SyncResult(written=False, reason=f"unreadable PRJ {prj_md.name}: {e}")
    replaced = replace_section(original, render_section(update, provenance))
    if replaced is None:
        return SyncResult(written=False, reason=f"{prj_md.name} has no '{SECTION_HEADER}' section")
    if replaced == original:
        return SyncResult(written=False, reason=f"{prj_md.name} unchanged")
    _atomic_write(prj_md, bump_updated(replaced, date_str))
    return SyncResult(written=True, reason=f"{prj_md.name} section replaced")
