"""Tests for built-in post-compact hook."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path

HOOK_PATH = (
    Path(__file__).parent.parent.parent
    / "src"
    / "lazy_harness"
    / "hooks"
    / "builtins"
    / "post_compact.py"
)


def _run_hook(tmp_path: Path, stdin: str = "{}") -> subprocess.CompletedProcess[str]:
    env = {
        "PATH": os.environ.get("PATH", ""),
        "HOME": str(tmp_path),
        "CLAUDE_CONFIG_DIR": str(tmp_path / ".claude"),
    }
    return subprocess.run(
        [sys.executable, str(HOOK_PATH)],
        input=stdin,
        capture_output=True,
        text=True,
        cwd=str(tmp_path),
        timeout=10,
        env=env,
    )


def _memory_dir(tmp_path: Path) -> Path:
    cwd_str = str(tmp_path)
    encoded = "-" + cwd_str.replace("/", "-").lstrip("-")
    mem = tmp_path / ".claude" / "projects" / encoded / "memory"
    mem.mkdir(parents=True, exist_ok=True)
    return mem


def test_post_compact_injects_fresh_summary(tmp_path: Path) -> None:
    mem = _memory_dir(tmp_path)
    summary_file = mem / "pre-compact-summary.md"
    summary_file.write_text(
        "<!-- auto-generated by pre-compact hook at 2026-04-22T10:00:00 -->\n"
        "## Tasks in progress\n"
        "- refactor auth module\n"
        "## Files worked on\n"
        "- /repos/foo/auth.py\n"
    )

    result = _run_hook(tmp_path)

    assert result.returncode == 0
    assert result.stdout.strip(), "expected non-empty stdout when summary is fresh"
    payload = json.loads(result.stdout)
    hso = payload["hookSpecificOutput"]
    assert hso["hookEventName"] == "PostCompact"
    body = hso["additionalContext"]
    assert "Tasks in progress" in body
    assert "refactor auth module" in body
    assert "/repos/foo/auth.py" in body
    assert "<!--" not in body, "HTML comment should be stripped"


def test_post_compact_skips_when_summary_missing(tmp_path: Path) -> None:
    # Memory dir does not even exist; hook must not crash.
    (tmp_path / ".claude").mkdir()

    result = _run_hook(tmp_path)

    assert result.returncode == 0
    assert result.stdout.strip() == "", "no output expected when summary is missing"


def test_post_compact_skips_when_summary_stale(tmp_path: Path) -> None:
    mem = _memory_dir(tmp_path)
    summary_file = mem / "pre-compact-summary.md"
    summary_file.write_text("<!-- old -->\n## Tasks in progress\n- something old\n")
    # Force mtime to 10 minutes ago — well past the 300s freshness window.
    ten_minutes_ago = time.time() - 600
    os.utime(summary_file, (ten_minutes_ago, ten_minutes_ago))

    result = _run_hook(tmp_path)

    assert result.returncode == 0
    assert result.stdout.strip() == "", "no output expected when summary is stale"


def test_post_compact_exit_zero_on_empty_stdin(tmp_path: Path) -> None:
    (tmp_path / ".claude").mkdir()

    result = subprocess.run(
        [sys.executable, str(HOOK_PATH)],
        input="",
        capture_output=True,
        text=True,
        cwd=str(tmp_path),
        timeout=10,
    )

    assert result.returncode == 0


def test_post_compact_routes_paths_through_agent_adapter(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """ADR-032 L3/L4: the summary location must come from the configured agent
    adapter. With agent.type = "null" it must be read from under ~/.null even
    when CLAUDE_CONFIG_DIR points elsewhere."""
    import io
    import sys as _sys

    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "decoy-claude"))

    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    mem = home / ".null" / "projects" / encoded / "memory"
    mem.mkdir(parents=True)
    (mem / "pre-compact-summary.md").write_text(
        "<!-- auto -->\n## Tasks in progress\n- adapter routing\n"
    )

    cfg_file = tmp_path / "config.toml"
    cfg_file.write_text('[harness]\nversion = "1"\n\n[agent]\ntype = "null"\n')
    from lazy_harness.core import paths as paths_mod
    from lazy_harness.hooks.builtins import post_compact as hook_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_file)
    monkeypatch.chdir(cwd)
    monkeypatch.setattr(_sys, "stdin", io.StringIO("{}"))
    hook_mod.main()

    out = capsys.readouterr().out
    assert out.strip(), "expected injected summary from the agent-adapter dir"
    payload = json.loads(out)
    assert "adapter routing" in payload["hookSpecificOutput"]["additionalContext"]
