"""Tests for built-in post-compact hook."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path

HOOK_PATH = (
    Path(__file__).parent.parent.parent
    / "src"
    / "lazy_harness"
    / "hooks"
    / "builtins"
    / "post_compact.py"
)


def _run_hook(tmp_path: Path, stdin: str = "{}") -> subprocess.CompletedProcess[str]:
    env = {
        "PATH": os.environ.get("PATH", ""),
        "HOME": str(tmp_path),
        "CLAUDE_CONFIG_DIR": str(tmp_path / ".claude"),
    }
    return subprocess.run(
        [sys.executable, str(HOOK_PATH)],
        input=stdin,
        capture_output=True,
        text=True,
        cwd=str(tmp_path),
        timeout=10,
        env=env,
    )


def _memory_dir(tmp_path: Path) -> Path:
    cwd_str = str(tmp_path)
    encoded = "-" + cwd_str.replace("/", "-").lstrip("-")
    mem = tmp_path / ".claude" / "projects" / encoded / "memory"
    mem.mkdir(parents=True, exist_ok=True)
    return mem


def test_post_compact_injects_fresh_summary(tmp_path: Path) -> None:
    mem = _memory_dir(tmp_path)
    summary_file = mem / "pre-compact-summary.md"
    summary_file.write_text(
        "<!-- auto-generated by pre-compact hook at 2026-04-22T10:00:00 -->\n"
        "## Tasks in progress\n"
        "- refactor auth module\n"
        "## Files worked on\n"
        "- /repos/foo/auth.py\n"
    )

    result = _run_hook(tmp_path)

    assert result.returncode == 0
    assert result.stdout.strip(), "expected non-empty stdout when summary is fresh"
    payload = json.loads(result.stdout)
    hso = payload["hookSpecificOutput"]
    assert hso["hookEventName"] == "PostCompact"
    body = hso["additionalContext"]
    assert "Tasks in progress" in body
    assert "refactor auth module" in body
    assert "/repos/foo/auth.py" in body
    assert "<!--" not in body, "HTML comment should be stripped"


def test_post_compact_skips_when_summary_missing(tmp_path: Path) -> None:
    # Memory dir does not even exist; hook must not crash.
    (tmp_path / ".claude").mkdir()

    result = _run_hook(tmp_path)

    assert result.returncode == 0
    assert result.stdout.strip() == "", "no output expected when summary is missing"
