"""Tests for built-in session-end hook."""

from __future__ import annotations

import json
from pathlib import Path

import pytest


def _interactive_session_jsonl(sessions_dir: Path, session_id: str) -> Path:
    session = sessions_dir / f"{session_id}.jsonl"
    records = [
        {"type": "permission-mode"},
        {"type": "system", "cwd": str(sessions_dir)},
        {"type": "user", "message": {"content": "a" * 250}},
        {"type": "assistant", "message": {"content": "ok"}},
    ]
    session.write_text("\n".join(json.dumps(r) for r in records) + "\n")
    return session


def _write_minimal_config(claude_dir: Path) -> Path:
    """Emit a minimal lh.toml so load_config succeeds with compound_loop enabled."""
    cfg_dir = claude_dir / "lazy-harness"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_file = cfg_dir / "config.toml"
    cfg_file.write_text(
        """
[harness]
version = "1"

[agent]
type = "claude-code"

[profiles]
default = "test"

[profiles.test]
config_dir = "~/.claude-test"
roots = ["~"]

[compound_loop]
enabled = true
debounce_seconds = 60
reprocess_min_growth_seconds = 120
"""
    )
    return cfg_file


def _patch_config_lookup(monkeypatch: pytest.MonkeyPatch, claude_dir: Path) -> None:
    cfg_file = _write_minimal_config(claude_dir)
    from lazy_harness.core import paths as paths_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_file)


def _run_session_end(monkeypatch: pytest.MonkeyPatch, claude_dir: Path, cwd: Path) -> None:
    """Invoke session_end.main() in a controlled environment.

    stdin is replaced with '{}' so the JSON parse in main() succeeds, and
    subprocess.Popen is stubbed to a no-op to avoid spawning a real worker.
    """
    import io

    from lazy_harness.hooks.builtins import session_end as hook_mod

    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO("{}"))
    monkeypatch.setattr(hook_mod.subprocess, "Popen", lambda *a, **kw: None)
    with pytest.raises(SystemExit) as exc:
        hook_mod.main()
    assert exc.value.code == 0


def test_session_end_hook_queues_task_even_when_debounced(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Force path: a freshly-queued task must not suppress a SessionEnd run.

    Regression guard for the original bug: Stop events within the debounce
    window swallowed the final handoff refresh. SessionEnd must override that.
    """
    import time

    from lazy_harness.knowledge.compound_loop import create_task

    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    sessions_dir = claude_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    session = _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0001")

    # Simulate a Stop hook task queued 5s ago — within the debounce window.
    # Rename to an earlier timestamp so the session-end task doesn't collide
    # with the same `{now}-{short_id}.task` filename generated by create_task.
    queue_dir = claude_dir / "queue"
    stale_task = create_task(
        queue_dir,
        cwd,
        session,
        "abcd1234-deadbeef-0001",
        sessions_dir / "memory",
    )
    earlier_name = queue_dir / f"{int(time.time()) - 5}-abcd1234.task"
    stale_task.rename(earlier_name)
    tasks_before = set(queue_dir.glob("*.task"))
    assert len(tasks_before) == 1

    _patch_config_lookup(monkeypatch, claude_dir)
    _run_session_end(monkeypatch, claude_dir, cwd)

    tasks_after = set(queue_dir.glob("*.task"))
    new_tasks = tasks_after - tasks_before
    assert len(new_tasks) == 1, (
        "session-end must enqueue a fresh task even inside the debounce window"
    )


def test_session_end_hook_skips_when_compound_loop_disabled(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    sessions_dir = claude_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0002")
    queue_dir = claude_dir / "queue"
    queue_dir.mkdir()

    cfg_dir = claude_dir / "lazy-harness"
    cfg_dir.mkdir()
    (cfg_dir / "config.toml").write_text(
        """
[harness]
version = "1"

[agent]
type = "claude-code"

[compound_loop]
enabled = false
"""
    )
    from lazy_harness.core import paths as paths_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_dir / "config.toml")
    _run_session_end(monkeypatch, claude_dir, cwd)

    assert list(queue_dir.glob("*.task")) == []


def test_session_end_routes_paths_through_agent_adapter(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """ADR-032 L3/L4: dirs must come from the configured agent adapter, not
    from a hardcoded CLAUDE_CONFIG_DIR read. With agent.type = "null" (no env
    var, no global link) resolution must land under ~/.null even when
    CLAUDE_CONFIG_DIR points elsewhere."""
    import io

    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    decoy_dir = tmp_path / "decoy-claude"

    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    agent_dir = home / ".null"
    sessions_dir = agent_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0003")

    cfg_file = tmp_path / "config.toml"
    cfg_file.write_text(
        """
[harness]
version = "1"

[agent]
type = "null"

[compound_loop]
enabled = true
"""
    )
    from lazy_harness.core import paths as paths_mod
    from lazy_harness.hooks.builtins import session_end as hook_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_file)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(decoy_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO("{}"))
    monkeypatch.setattr(hook_mod.subprocess, "Popen", lambda *a, **kw: None)
    with pytest.raises(SystemExit) as exc:
        hook_mod.main()
    assert exc.value.code == 0

    assert len(list((agent_dir / "queue").glob("*.task"))) == 1
    assert not (decoy_dir / "queue").exists()


def test_session_end_hook_skips_when_no_session_found(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    # No sessions_dir created → no .jsonl anywhere.
    queue_dir = claude_dir / "queue"

    _patch_config_lookup(monkeypatch, claude_dir)
    _run_session_end(monkeypatch, claude_dir, cwd)

    assert not queue_dir.exists() or list(queue_dir.glob("*.task")) == []


def test_records_session_closed(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A session_closed loop event is recorded regardless of whether the
    compound-loop enqueue itself finds a session to act on."""
    import io

    from lazy_harness.hooks.builtins import session_end as hook_mod
    from lazy_harness.monitoring.db import MetricsDB

    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    db_path = tmp_path / "m.db"

    monkeypatch.setattr(hook_mod, "_loop_db_path", lambda: db_path)
    _patch_config_lookup(monkeypatch, claude_dir)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps({"session_id": "s1"})))
    monkeypatch.setattr(hook_mod.subprocess, "Popen", lambda *a, **kw: None)

    with pytest.raises(SystemExit) as exc:
        hook_mod.main()
    assert exc.value.code == 0

    assert MetricsDB(db_path).loop_event_counts() == {"session_closed": 1}


def test_still_exits_zero_and_still_enqueues_when_recording_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A metrics-store failure while recording session_closed must not
    prevent the existing compound-loop enqueue from running — this is the
    ordering constraint the hook exists to preserve."""
    import io

    from lazy_harness.hooks.builtins import session_end as hook_mod

    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    sessions_dir = claude_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0004")
    queue_dir = claude_dir / "queue"

    blocked = tmp_path / "not-a-dir"
    blocked.write_text("x")
    monkeypatch.setattr(hook_mod, "_loop_db_path", lambda: blocked / "m.db")

    _patch_config_lookup(monkeypatch, claude_dir)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps({"session_id": "s1"})))
    monkeypatch.setattr(hook_mod.subprocess, "Popen", lambda *a, **kw: None)

    with pytest.raises(SystemExit) as exc:
        hook_mod.main()
    assert exc.value.code == 0

    assert len(list(queue_dir.glob("*.task"))) == 1


def test_main_exits_zero_even_when_enqueue_raises_uncaught_exception(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Any exception inside _enqueue_compound_loop that is not explicitly
    caught must not escape main() — the hook must degrade gracefully and
    exit 0 rather than crashing the Claude Code shutdown chain.

    This test triggers a KeyError, which is not in the current exception
    handlers (ImportError, ConfigError, OSError).
    """
    import io

    from lazy_harness.hooks.builtins import session_end as hook_mod

    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()

    _patch_config_lookup(monkeypatch, claude_dir)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO("{}"))

    # Monkeypatch get_agent to raise KeyError — an exception type
    # that _enqueue_compound_loop does not currently catch.
    def raise_keyerror(*args: object, **kwargs: object) -> object:
        raise KeyError("simulated uncaught exception in get_agent")

    from lazy_harness.agents import registry as registry_mod

    monkeypatch.setattr(registry_mod, "get_agent", raise_keyerror)

    # main() must still raise SystemExit with code 0, not let the KeyError escape.
    with pytest.raises(SystemExit) as exc:
        hook_mod.main()
    assert exc.value.code == 0
