"""Tests for built-in session-end hook."""

from __future__ import annotations

import json
from pathlib import Path

import pytest


def _interactive_session_jsonl(sessions_dir: Path, session_id: str) -> Path:
    session = sessions_dir / f"{session_id}.jsonl"
    records = [
        {"type": "permission-mode"},
        {"type": "system", "cwd": str(sessions_dir)},
        {"type": "user", "message": {"content": "a" * 250}},
        {"type": "assistant", "message": {"content": "ok"}},
    ]
    session.write_text("\n".join(json.dumps(r) for r in records) + "\n")
    return session


def _write_minimal_config(claude_dir: Path) -> Path:
    """Emit a minimal lh.toml so load_config succeeds with compound_loop enabled."""
    cfg_dir = claude_dir / "lazy-harness"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_file = cfg_dir / "config.toml"
    cfg_file.write_text(
        """
[harness]
version = "1"

[agent]
type = "claude-code"

[profiles]
default = "test"

[profiles.test]
config_dir = "~/.claude-test"
roots = ["~"]

[compound_loop]
enabled = true
debounce_seconds = 60
reprocess_min_growth_seconds = 120
"""
    )
    return cfg_file


def _patch_config_lookup(
    monkeypatch: pytest.MonkeyPatch, claude_dir: Path
) -> None:
    cfg_file = _write_minimal_config(claude_dir)
    from lazy_harness.core import paths as paths_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_file)


def _run_session_end(
    monkeypatch: pytest.MonkeyPatch, claude_dir: Path, cwd: Path
) -> None:
    """Invoke session_end.main() in a controlled environment.

    stdin is replaced with '{}' so the JSON parse in main() succeeds, and
    subprocess.Popen is stubbed to a no-op to avoid spawning a real worker.
    """
    import io

    from lazy_harness.hooks.builtins import session_end as hook_mod

    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(claude_dir))
    monkeypatch.chdir(cwd)
    monkeypatch.setattr("sys.stdin", io.StringIO("{}"))
    monkeypatch.setattr(hook_mod.subprocess, "Popen", lambda *a, **kw: None)
    hook_mod.main()


def test_session_end_hook_queues_task_even_when_debounced(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Force path: a freshly-queued task must not suppress a SessionEnd run.

    Regression guard for the original bug: Stop events within the debounce
    window swallowed the final handoff refresh. SessionEnd must override that.
    """
    import time

    from lazy_harness.knowledge.compound_loop import create_task

    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    sessions_dir = claude_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    session = _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0001")

    # Simulate a Stop hook task queued 5s ago — within the debounce window.
    # Rename to an earlier timestamp so the session-end task doesn't collide
    # with the same `{now}-{short_id}.task` filename generated by create_task.
    queue_dir = claude_dir / "queue"
    stale_task = create_task(
        queue_dir,
        cwd,
        session,
        "abcd1234-deadbeef-0001",
        sessions_dir / "memory",
    )
    earlier_name = queue_dir / f"{int(time.time()) - 5}-abcd1234.task"
    stale_task.rename(earlier_name)
    tasks_before = set(queue_dir.glob("*.task"))
    assert len(tasks_before) == 1

    _patch_config_lookup(monkeypatch, claude_dir)
    _run_session_end(monkeypatch, claude_dir, cwd)

    tasks_after = set(queue_dir.glob("*.task"))
    new_tasks = tasks_after - tasks_before
    assert len(new_tasks) == 1, (
        "session-end must enqueue a fresh task even inside the debounce window"
    )


def test_session_end_hook_skips_when_compound_loop_disabled(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    encoded = "-" + str(cwd).replace("/", "-").lstrip("-")
    sessions_dir = claude_dir / "projects" / encoded
    sessions_dir.mkdir(parents=True)
    _interactive_session_jsonl(sessions_dir, "abcd1234-deadbeef-0002")
    queue_dir = claude_dir / "queue"
    queue_dir.mkdir()

    cfg_dir = claude_dir / "lazy-harness"
    cfg_dir.mkdir()
    (cfg_dir / "config.toml").write_text(
        """
[harness]
version = "1"

[agent]
type = "claude-code"

[compound_loop]
enabled = false
"""
    )
    from lazy_harness.core import paths as paths_mod

    monkeypatch.setattr(paths_mod, "config_file", lambda: cfg_dir / "config.toml")
    _run_session_end(monkeypatch, claude_dir, cwd)

    assert list(queue_dir.glob("*.task")) == []


def test_session_end_hook_skips_when_no_session_found(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    claude_dir = tmp_path / ".claude-test"
    cwd = tmp_path / "proj"
    cwd.mkdir()
    # No sessions_dir created → no .jsonl anywhere.
    queue_dir = claude_dir / "queue"

    _patch_config_lookup(monkeypatch, claude_dir)
    _run_session_end(monkeypatch, claude_dir, cwd)

    assert not queue_dir.exists() or list(queue_dir.glob("*.task")) == []
